### ISSUE TITLE
The code does not converge when the batch size is small

### ISSUE THREAD

**Issue by sccdnmj** [szq0214/FKD#1]
Dear author, hello! The default batch size of your code is 1024. I found in experiments that the code does not converge when the batch size is set to 128 or 256.

**Comment by szq0214** [comment]
@sccdnmj, thanks very much for your interest in our work! 

Actually, this is a great question to grasp the mechanism and core of our proposed method.

This is, from my perspective, somewhat expected. Please keep in mind that as we use multiple crops from each image to compose a mini-batch, so the actual number of loaded images in a mini-batch will be #batch-size/#num_crops, that is to say, for bs=128 and num_crops=4, you actually only load 32 images in every mini-batch for one training iteration. This proposed technique can facilitate data loading and speed up training, but the drawback is that the diversity in a mini-batch will be lower than the vanilla strategy using 128 randomly-sampled images. It's alright if the batch size is large enough, but it will be amplified when the _bs_ is too small, and also the excessively small batch size on each GPU will harm BN training.

I suggest to train with bs=512, 1024, or larger. If you have to train with a small batch size for some reason, like GPU memory limit, there are two ways that may be effective to help this: **(i)** add **_warmup_** technique which is not used in our basic setting on ResNet; **(ii)** try to use smaller _--num_crops_ hyperparameter, for instance, set **_--num_crops 1_** (I have a quick test on bs=128, num_crops=1 with one GPU, the model starts to converge well).
